apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "classifierbot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "classifierbot.name" . }}
    helm.sh/chart: {{ include "classifierbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "classifierbot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "classifierbot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BOTPRESS_PORT
              value: "{{ .Values.botpress.port }}"
            - name: BOTPRESS_ENV
              value: "{{ .Values.botpress.env }}"
            - name: ROCKETCHAT_URL
              value: "{{ .Values.botpress.rocketchat.url }}"
            - name: ROCKETCHAT_USER
              value: "{{ .Values.botpress.rocketchat.user }}"
            - name: ROCKETCHAT_PASSWORD
              value: "{{ .Values.botpress.rocketchat.passwd }}"
            - name: ROCKETCHAT_USE_SSL
              value: "{{ .Values.botpress.rocketchat.usessl }}"
            - name: ROCKETCHAT_ROOM
              value: "{{ .Values.botpress.rocketchat.room }}"
            - name: NLU_PROVIDER
              value: "rasa"
            - name: NLU_RASA_URL
              value: "http://{{ .Release.Name }}-rasa:{{ .Values.rasa.service.port }}/"
          ports:
            - name: classifierbot
              containerPort: {{ .Values.botpress.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.botpress.port }}
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.botpress.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
