apiVersion: v1
kind: Service
metadata:
  name: {{ include "classifierbot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "classifierbot.name" . }}
    helm.sh/chart: {{ include "classifierbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.botpress.port }}
      protocol: TCP
      name: continuous-bot
  selector:
    app.kubernetes.io/name: {{ include "classifierbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
